In [1]:
import pandas as pd

# Ganti nama_file_mobil.csv dengan nama file aslimu
df = pd.read_csv('jdm_used_cars.csv') 
df.head()

,Unnamed: 0,price,mark,model,year,mileage,engine_capacity,transmission,drive,hand_drive,fuel
0,0,80,nissan,march,2003,80000,1240,at,2wd,rhd,gasoline
1,1,110,nissan,march,2010,53000,1200,at,2wd,rhd,gasoline
2,2,165,nissan,lafesta,2005,47690,2000,at,2wd,rhd,gasoline
3,3,190,toyota,avensis,2008,130661,1990,at,2wd,rhd,gasoline
4,4,190,daihatsu,mira,2006,66300,660,at,2wd,rhd,gasoline

In [2]:
# Menampilkan dimensi dataset (baris, kolom)
print(f"Dimensi dataset: {df.shape[0]} baris, {df.shape[1]} kolom")

# Menampilkan 5 baris pertama dan 5 baris sampel acak
display(df.head())
display(df.sample(5, random_state=42))

Dimensi dataset: 2318 baris, 11 kolom

,Unnamed: 0,price,mark,model,year,mileage,engine_capacity,transmission,drive,hand_drive,fuel
0,0,80,nissan,march,2003,80000,1240,at,2wd,rhd,gasoline
1,1,110,nissan,march,2010,53000,1200,at,2wd,rhd,gasoline
2,2,165,nissan,lafesta,2005,47690,2000,at,2wd,rhd,gasoline
3,3,190,toyota,avensis,2008,130661,1990,at,2wd,rhd,gasoline
4,4,190,daihatsu,mira,2006,66300,660,at,2wd,rhd,gasoline

,Unnamed: 0,price,mark,model,year,mileage,engine_capacity,transmission,drive,hand_drive,fuel
1040,1050,950,nissan,tiida,2011,73000,1500,at,2wd,rhd,gasoline
548,552,760,honda,fit,2005,78000,1330,at,2wd,rhd,gasoline
100,102,400,daihatsu,tanto,2012,183800,660,at,2wd,rhd,gasoline
1044,1054,950,toyota,brevis,2001,76000,2990,at,2wd,rhd,gasoline
251,255,560,honda,fit,2004,74200,1300,at,2wd,rhd,gasoline

In [3]:
# Mengecek tipe data setiap kolom dan memori yang digunakan
print("--- Informasi Dataset ---")
df.info()

# Menghitung persentase missing values per kolom
print("\n--- Persentase Missing Values ---")
missing_data = df.isnull().sum()
missing_percent = (missing_data / len(df)) * 100
missing_df = pd.DataFrame({'Total Kosong': missing_data, 'Persentase (%)': missing_percent})
display(missing_df[missing_df['Total Kosong'] > 0].sort_values(by='Persentase (%)', ascending=False))

--- Informasi Dataset ---
<class 'pandas.DataFrame'>
RangeIndex: 2318 entries, 0 to 2317
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       2318 non-null   int64
 1   price            2318 non-null   int64
 2   mark             2318 non-null   str
 3   model            2318 non-null   str
 4   year             2318 non-null   int64
 5   mileage          2318 non-null   int64
 6   engine_capacity  2318 non-null   int64
 7   transmission     2318 non-null   str
 8   drive            2318 non-null   str
 9   hand_drive       2318 non-null   str
 10  fuel             2318 non-null   str
dtypes: int64(5), str(6)
memory usage: 199.3 KB

--- Persentase Missing Values ---

Empty DataFrame
Columns: [Total Kosong, Persentase (%)]
Index: []

In [4]:
# Mengecek dan menghapus duplikasi data (jika ada)
jumlah_duplikat = df.duplicated().sum()
print(f"Jumlah baris duplikat: {jumlah_duplikat}")

if jumlah_duplikat > 0:
    df = df.drop_duplicates(keep='first')
    print("Baris duplikat berhasil dihapus.")

# Melihat ringkasan statistik (fokus pada kolom numerik)
display(df.describe())

Jumlah baris duplikat: 0

        Unnamed: 0        price         year        mileage  engine_capacity
count  2318.000000  2318.000000  2318.000000    2318.000000      2318.000000
mean   1169.047023   971.522433  2005.972390  100013.194996      1507.010785
std     674.460724   288.673112     3.698863   52512.478883       549.585170
min       0.000000    80.000000  1979.000000    2000.000000         9.000000
25%     583.250000   776.000000  2004.000000   67000.000000      1300.000000
50%    1168.500000  1000.000000  2006.000000   94000.000000      1490.000000
75%    1753.750000  1213.000000  2009.000000  124000.000000      1800.000000
max    2335.000000  1400.000000  2015.000000  790000.000000     12340.000000